backend:
  name: github
  repo: your Github username/ your repo name

media_folder: static/assets
public_folder: /assets
extension: mdx
format: frontmatter
identifier_field: name
collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
